posts/urls.py
from django.urls import path, include


from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
)


urlpatterns = [
    path('<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('create/', PostCreateView.as_view(), name='post_create'),
    path('', PostListView.as_view(), name='post_list'),
]

tryDjangoBlog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('comments/', include('comments.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.contrib.contenttypes.models import ContentType

from markdown_deux import markdown


from comments.models import Comment
from .utils import get_read_time


def upload_location(instance, filename):
    return '%s/%s' % (instance.id, filename)


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    image = models.ImageField(upload_to=upload_location,
                              null=True,
                              blank=True,
                              width_field='width_field',
                              height_field='height_field')
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    read_time = models.IntegerField(default=0)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post_detail', args = str(self.id))

    class Meta:
        ordering = ['-timestamp', '-updated']

    def get_markdown(self):
        content = self.content
        markdown_text = markdown(content)
        return mark_safe(markdown_text)

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if instance.content:
        html_string = instance.get_markdown()
        read_time = get_read_time(html_string)
        instance.read_time = read_time

pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
from django import forms

from pagedown.widgets import PagedownWidget

from .models import Post


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))

    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'image',
        ]

templates/base.html
{% load staticfiles %}


<!doctype html>
<html>
    <head>
        <title>{% block title %}TryDjango blog{% endblock title %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/base.css' %}" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />

        {% block head_extra %}{% endblock head_extra %}
    </head>
    <body>
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
             var js, fjs = d.getElementsByTagName(s)[0];
             if (d.getElementById(id)) return;
             js = d.createElement(s); js.id = id;
             js.src = 'https://connect.facebook.net/ru_RU/sdk.js#xfbml=1&version=v3.2';
             fjs.parentNode.insertBefore(js, fjs);
         }(document, 'script', 'facebook-jssdk'));</script>
        

        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active">
                    <a href="{% url 'post_list' %}">Home</a>
                </li>
                {% block post_detail_link %}
                {% endblock post_detail_link %}

                {% if not user.is_authenticated %}
                <li class="breadcrumb-item active ml-auto">
                    <a href="{% url 'signup' %}">Register</a>
                </li>
                <li class="breadcrumb-item active">
                    <a href="{% url 'login' %}">Login</a>
                </li>
                {% else %}
                <li class="breadcrumb-item ml-auto">
                    {{ user }}
                </li>
                <li class="breadcrumb-item active">
                    <a href="{% url 'logout' %}">Logout</a>
                </li>
                {% endif %}
            </ol>

            {% block content %}
            {% endblock content %}
        </div>

        <script
            src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.6.0/marked.js"></script>
        <script type="text/javascript">
         $(document).ready(function(){
             $(".content-markdown").each(function(){
                 var content = $(this).text()
                 console.log(content)
                 var markedContent = marked(content)
                 console.log(markedContent)
                 $(this).html(markedContent)
             })

             $(".post-detail-item img").each(function(){
                 $("img").addClass("img-fluid")
             })

             // ==============================================

             var contentInput = $('#id_content')

             function setContent(value){
                 var markedContent = marked(value)
                 $('#preview-content').html(markedContent)
                 $('#preview-content img').each(function(){
                     $(this).addClass('img-fluid')
                 })
             }
             setContent(contentInput.val())

             contentInput.keyup(function(){
                 var newContent = $(this).val()
                 setContent(newContent)
             })

             var titleInput = $('#id_title')

             function setTitle(value){
                 $('#preview-title').text(value)
             }
             setTitle(titleInput.val())

             titleInput.keyup(function(){
                 var newTitle = $(this).val()
                 setTitle(newTitle)
             })

             // ==========================================

             $('.comment-reply-btn').click(function(event){
                 event.preventDefault()
                 $(this).parent().next('.comment-reply').fadeToggle();
             })
         })
         </script>
    </body>
</html>

templates/comment_delete.html
{% extends 'base.html' %}


{% load crispy_forms_tags %}


{% block title %}Confirm delete{% endblock title %}


{% block post_detail_link %}
    {% if object.parent %}
        <li class="breadcrumb-item active">
            <a href="{% url 'post_detail' object.parent.content_object.pk %}">{{ object.parent.content_object.title }}</a>
        </li>
        <li class="breadcrumb-item active">
            <a href="{% url 'thread' object.parent.pk %}">Comment thread</a>
        </li>
        <li class="breadcrumb-item" aria-current="page">
            Delete comment
        </li>
    {% else %}
        <li class="breadcrumb-item active">
            <a href="{% url 'post_detail' object.content_object.pk %}">{{ comment.content_object.title }}</a>
        </li>
        <li class="breadcrumb-item active">
            <a href="{% url 'thread' object.pk %}">Comment thread</a>
        </li>
        <li class="breadcrumb-item" aria-current="page">
            Delete comment
        </li>
    {% endif %}
{% endblock post_detail_link %}


{% block content %}
    <div class="col-sm-6 mx-auto">
        <h1>Confirm delete</h1>
        <form method="POST">{% csrf_token %}
            {{ form|crispy }}
            <p>
                Are you sure want to delete '{{ object.content }}'
            </p>
            <input class="btn btn-danger" type="submit" value="Confirm"/>
            <a href="{% if object.parent %}{% url 'thread' object.parent.pk %}{% else %}{% url 'thread' object.pk %}{% endif %}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
{% endblock content %}

templates/comment_detail.html
{% extends 'base.html' %}


{% load crispy_forms_tags %}


{% block post_detail_link %}
<li class="breadcrumb-item active">
    <a href="{% url 'post_detail' comment.content_object.pk %}">{{ comment.content_object.title }}</a>
</li>
<li class="breadcrumb-item" aria-current="page">
    Comment thread
</li>
{% endblock post_detail_link %}


{% block content %}
    <div class="col-sm-6 mx-auto">
        <p>
            {{ comment.content }}
        </p>
        <cite>via {{ comment.user }}
            | {{ comment.timestamp|timesince }} ago
            | {% if comment.children.count > 0 %}
            {{ comment.children.count }} Comment{% if comment.children.count >= 1 %}s{% endif %}
            {% endif %}
            {% if user == comment.user %} <a href="{% url 'comment_delete' comment.pk %}">Delete</a>{% endif %}
        </cite>

        <hr/>

        <div>
            {% for child_comment in comment.children %}
                <blockquote class="blockquote ml-5">
                    <p class="mb-0">
                        {{ child_comment.content }}
                    </p>
                    <cite>
                        via {{ child_comment.user }} | {{ child_comment.timestamp|timesince }} ago
                        {% if user == child_comment.user %} <a href="{% url 'comment_delete' child_comment.pk %}">Delete</a>{% endif %}
                    </cite>
                </blockquote>
            {% endfor %}

            {% if user.is_authenticated %}
                <form method="POST" action=".">{% csrf_token %}
                    {{ comment_form|crispy }}
                    <input name="parent_id" type="hidden" value="{{ comment.id }}"/>
                    <input class="btn btn-primary" type="submit" value="Post comment"/>
                </form>
            {% else %}
                {% if comment.children %}
                    <hr/>
                {% endif %}
                <p>
                    You must login to comment
                </p>
            {% endif %}
        </div>
        <hr/>
    </div>
{% endblock content %}

templates/post_create.html
{% extends 'base.html' %}


{% load crispy_forms_tags %}


{% block title %}Create post{% endblock title %}


{% block head_extra %}

    {{ form.media }}

{% endblock head_extra %}


{% block post_detail_link %}
    <li class="breadcrumb-item" aria-current="page">
        <span style="color: green;">Create new post</span>
    </li>
{% endblock post_detail_link %}


{% block content %}
    <div class="row">
        <div class="col-sm-6">
            <h1>Preview</h1>
            <hr/>
            <div class="content-preview">
                <h3 id="preview-title"></h3>
                <p id="preview-content"></p>
            </div>
        </div>

        <div class="col-sm-6">
            <h1>Create Post</h1>
            <form method="post" enctype="multipart/form-data">{% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Create Post</button>
            </form>
        </div>
    </div>
{% endblock content %}

templates/post_delete.html
{% extends 'base.html' %}


{% block title %}{{object.title}}{% endblock title %}


{% block post_detail_link %}
<li class="breadcrumb-item active">
    <a href="{% url 'post_detail' object.pk %}">{{ object.title }}</a>
</li>
<li class="breadcrumb-item" aria-current="page">
    <span style="color: red;">Delete</span>
</li>
{% endblock post_detail_link %}


{% block content %}
    <div class="col-sm-4 mx-auto">
        <h1>Delete post</h1>
        <form method="post">{% csrf_token %}
            <p>
                Are you sure you want to delete "{{ object.title }}"?
            </p>
            <button class="btn btn-danger ml-2" type="submit">Confirm</button>
        </form>
    </div>
{% endblock content %}

templates/post_detail.html
{% extends 'base.html' %}


{% load urlify %}
{% load crispy_forms_tags %}


{% block title %}{{ object.title }} | {{ block.super }}{% endblock title %}


{% block post_detail_link %}
<li class="breadcrumb-item" aria-current="page">
    {{ object.title }}
</li>
{% endblock post_detail_link %}


{% block content %}
    <div class="col-md-6 mx-auto">
        {% if object.image %}
            <img src="{{ object.image.url }}" class="img-fluid" />
            <hr/>
        {% endif %}
        <h1>{{ object.title }} <small>{{ object.timestamp }}</small></h1>
        <hr/>

        <p>
            Read time: {% if object.read_time <= 1 %} < 1 min. {% else %}{{ object.read_time }} min.{% endif %}
        </p>

        <p>
            Author: {{ object.user }}
        </p>

        <p><div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div></p>

        <hr/>

        <div class="post-detail-item">{{ object.get_markdown|linebreaks }}</div>

        <hr/>
        <br/>

        <div>
            <p class="lead">
                Comments
            </p>

            {% if user.is_authenticated %}
                <form method="POST" action=".">{% csrf_token %}
                    {{ comment_form|crispy }}
                    <input class="btn btn-primary" type="submit" value="Post comment"/>
                </form>
            {% else %}
                <hr/>
                <p>
                    You must login to comment
                </p>
                <hr/>
            {% endif %}

            {% for comment in comments %}
                <blockquote>
                    <p>
                        {{ comment.content }}
                    </p>
                    <cite>via {{ comment.user }}
                        | {{ comment.timestamp|timesince }} ago
                        | {% if comment.children.count > 0 %}
                            {{ comment.children.count }} Comment{% if comment.children.count >= 1 %}s{% endif %}
                        | {% endif %} <a class="comment-reply-btn" href="#">Reply</a>
                        | <a href="{% url 'thread' comment.pk %}">Thread</a>
                        {% if user == comment.user %} | <a href="{% url 'comment_delete' comment.pk %}">Delete</a>{% endif %}
                    </cite>

                    <div class="comment-reply">
                        {% for child_comment in comment.children %}
                            <blockquote class="blockquote ml-5">
                                <p class="mb-0">
                                    {{ child_comment.content }}
                                </p>
                                <cite>
                                    via {{ child_comment.user }} | {{ child_comment.timestamp|timesince }} ago
                                    {% if user == child_comment.user %} | <a href="{% url 'comment_delete' child_comment.pk %}">Delete</a>{% endif %}
                                </cite>
                            </blockquote>
                        {% endfor %}

                        {% if user.is_authenticated %}
                            <form method="POST" action=".">{% csrf_token %}
                                {{ comment_form|crispy }}
                                <input name="parent_id" type="hidden" value="{{ comment.id }}"/>
                                <input class="btn btn-primary" type="submit" value="Post comment"/>
                            </form>
                        {% else %}
                            <hr/>
                            <p>
                                You must login to comment
                            </p>
                        {% endif %}
                    </div>

                </blockquote>
                <hr/>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

templates/post_update.html
{% extends 'base.html' %}


{% load crispy_forms_tags %}


{% block title %}{{object.title}}{% endblock title %}


{% block head_extra %}

    {{ form.media }}

{% endblock head_extra %}


{% block content %}
    <div class="row">
        <div class="col-sm-6">
            <h1>Preview</h1>
            <hr/>
            <div class="content-preview">
                <h3 id="preview-title"></h3>
                <p id="preview-content"></p>
            </div>
        </div>

        <div class="col-sm-6">
            <h1>Update Post</h1>
            <hr/>
            <form method="post" enctype="multipart/form-data">{% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">Update Post</button>
            </form>
        </div>
    </div>
{% endblock content %}

templates/posts_list.html
{% extends 'base.html' %}


{% block title %}TryDjango blog{% endblock title %}


{% block content%}
        <div class="col-sm-6 mx-auto mt-1">
            <form method="get" class="row">
                <div class="input-group">
                    <input class="form-control" type="text" name="q" placeholder="Search posts" value="{{ request.GET.q }}" />
                    <span class="input-group-prepend">
                        <button class="btn btn-info" type="submit"><i class="fa fa-search"></i></button>
                    </span>
                </div>
            </form>
        </div>
        <br/>
        {% if object_list %}
            {% for post in object_list %}
                <div class="col-sm-6 mx-auto post-detail-item img-thumbnail">
                    <div class="img-caption">
                        {% if post.image %}
                            <img src="{{ post.image.url }}" class="img-fluid" />
                        {% endif %}
                        <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a> <small>{{ post.timestamp|timesince }} ago</small></h3>
                        <p>
                            Author: {{ post.user }}
                        </p>
                        {{ post.get_markdown|linebreaks|truncatewords_html:5 }}
                        <p><a href="{{ post.get_absolute_url }}" class="btn btn-primary" role="button">View</a></p>
                    </div>
                </div>
                <hr/>
            {% endfor %}
        {% else %}
                <p>
                    No posts were found.
                </p>
        {% endif %}


        {% if is_paginated %}
            <div class="pagination">
                <span class="page-links mx-auto">
                    {% if page_obj.has_previous %}
                    <a href="/posts?page={{ page_obj.previous_page_number }}&q={% if request.GET.q %}{{ request.GET.q }}{% endif %}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                    <a href="/posts?page={{ page_obj.next_page_number }}&q={% if request.GET.q %}{{ request.GET.q }}{% endif %}">next</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}
{% endblock content %}

templates/signup.html
{% extends 'base.html' %}


{% load crispy_forms_tags %}


{% block title %}Sign Up{% endblock title %}


{% block content %}
    <div class="col-sm-6 mx-auto">
        <h2>Sign Up</h2>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-success" type="submit">Sign Up</button>
        </form>
    </div>
{% endblock content %}